### ISSUE TITLE
Switching between different sets of cf-plex groups requires bash aliases

### ISSUE THREAD

**Issue by srbry** [EngineerBetter/cf-plex#3]
When using the cf-plex tool I often have requirements to change my group of targets, for example from multiple production cf's to multiple non-production ones.

In order to do this I have added the following to my profile:

```
NP_HOME=~/.cf/np
NP1_api='https://api.example1.com'
NP2_api='https://api.example2/com'
CF_USER='username'
CF_PASSWORD='password'
alias cf-np="export CF_PLEX_HOME=$NP_HOME; cf-plex add-api $NP1_API $CF_USER $CF_PASSWORD; cf-plex add-api $NP2_API $CF_USER $CF_PASSWORD"
```

**Comment by srbry** [comment]
Also, to make it usable and see what my current plex target it i change PS1 as so:

```
export PS1="\[\033]0;$MSYSTEM:${PWD//[^[:ascii:]]/?}\007\]\n\[\033[32m\]\u@\h \[\033[33m\]\w\$(__git_ps1)\[\033[0m\] [plex-\$(basename $CF_PLEX_HOME 2> /dev/null)]$"
```

**Comment by DanielJonesEB** [comment]
Thanks for detailing your use case. There are some stories in the icebox for groups, and I've been holding off playing them whilst trying to figure out what the best way of managing groups is.

Should the user set some state (the active group) that is then implicit in all further commands?

```
$ cf-plex add-api https://api.nonprod.com username password nonprod
$ cf-plex set-group nonprod
$ cf-plex delete-org org
```

The downside I can see with that is the sort of accidental targeting that is the problem with the regular CF CLI. You forget to change the active group, and next thing you know, you've baleeted half of your production orgs.

The alternative would be to be inspired by the targeting behaviour of Concourse's `fly` command:

```
$ cf-plex add-api https://api.nonprod.com username password nonprod
$ cf-plex -g nonprod delete-org org
```

The danger then becomes forgetting to specify a group and then accidentally targeting the 'default' group. Maybe there should be no default group? Maybe every API should be in a group, and groups should be mandatory?

**Comment by srbry** [comment]
I am all for the mandatory group option for safety.

It would be fairly easy to write aliases if specifying a -g parameter each time seemed too difficult, but again it would be safe, personally I would like to be able to do something like:

```
alias cf-np="cf-plex -g non-prod"
cf-np orgs
```

It is then a small amount of effort but very clear to me what I would be targetting

**Comment by DanielJonesEB** [comment]
Out-of-band, DHR suggested the default group being disabled if at least one group exists. I think that's a nice way of not burdening users with knowledge of the groups system, but giving people flexibility if desired. Combined with making `-g` mandatory if groups exist, I think that makes the most slip-proof implementation.

**Comment by DanielJonesEB** [comment]
Please check out v1.3.0, and let me know whether the changes therein satisfy your requirements.
